name: app-laravel-nginx

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Registry
      run:  echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag app-laravel:$(date +%s)
#    - name: Laravel command
#      run: docker run app-laravel:$(date +%s) /var/www/html/conf/entrypoint.sh
    - name: Tag Docker image
      run: echo "${{secrets.DOCKER_PATH_BASE}}" | docker tag ${{secrets.DOCKER_PATH_BASE}}/app-laravel:$(date +%s)
    - name: Push Docker image
      run: docker push ${{secrets.DOCKER_PATH_BASE}}/app-laravel:$(date +%s)
